function [Response, previousMessage] = MACLayerReceiver(...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits,...
    lookingForACK,...
    previousMessage...
    )

% This function is called when the node is just listening to the spectrum
% waiting for a message to be transmitted to them

%% Listen to the spectrum
% previousMessage will be updated for next run
[Response, previousMessage] = DLLayer(...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits,...
    previousMessage...
    );



%% Possible response messages
% 1.) Timeout
% 2.) Some message
if ~strcmp(Response,'Timeout') &&  ~strcmp(Response,'Duplicate')
    fprintf('###########################################\n');
    fprintf('MAC| Got message: %s\n',Response);
    if ~lookingForACK
        fprintf('MAC| Transmitting ACK\n');
        % Send ACK
        PHYTransmit(...
            ObjSDRuTransmitter,...
            ObjSDRuReceiver,...
            'ACK',...
            tx.samplingFreq...
            );
        
    end
elseif strcmp(Response,'Duplicate')
    fprintf('MAC| Transmitting ACK for dupe\n');
    % Send ACK
    PHYTransmit(...
        ObjSDRuTransmitter,...
        ObjSDRuReceiver,...
        'ACK',...
        tx.samplingFreq...
        );
end


end

