function testPHYReceive


[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX_2;

lookingForACK = 0;

% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';

fileNum = 49;%char(49)=='1'

for run = 1 : 1e8
    
    %MAC
    [message, previousMessage] = MACLayerReceiver(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        lookingForACK,...
        previousMessage...
        );
    
    % Are we done?
    if fileSink( message, ['/Users/travis/Git/sdruOFDM/sdruMixed/tx_rx/monet_hat',char(fileNum),'.jpg'] );
        fileNum = fileNum + 1;
        %break
    end
    
end

end