function testPHYReceive


[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX_2;

lookingForACK = 0;

% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';

% Open file to save data
coder.extrinsic('fopen','fwrite','fclose');
filename = 'output.jpg';
fid = fopen(filename);


for run = 1 : 1e8
    
    %MAC
    [message, previousMessage] = MACLayerReceiver(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        lookingForACK,...
        previousMessage...
        );
    % Are we done?
    if strcmp(message,'EOF')
        fclose(fid);
        break;
    else
        fwrite(fid,message);
    end
    
end

end