function testPHYTransmit(offsets, nodeNum)



[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX;



% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';


for run = 1 : 1e4
    %message = ['Random Message',char(96+run)];%Create different messages each times
    message = ['Random Message'];%Dont create different messages each times
    
    previousMessage = MACLayerTransmitter(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        message,...
        previousMessage...
        );
    
    %Wait some time
    waitTime = .2e2; % Calculated in seconds buts thats far from realistic 
    fprintf('TOP| DONE Iteration: Waiting some time between actions\n');
    fprintf('Transmitted: %d\n',int32(run));
    Wait(ObjSDRuReceiver,tx.samplingFreq,waitTime);
    
    
end


end
