function testPHYTransmit



[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX;



% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';


for run = 1 : 1e4
    message = ['Random Message',char(96+run)];
    previousMessage = MACLayerTransmitter(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        message,...
        previousMessage...
        );
    
    %Wait some time
    fprintf('TOP| Waiting some time between actions\n');
    Wait(ObjSDRuReceiver,tx.samplingFreq,1e4);
    
    
end


end