function testPHYReceive(nodeOffsetTable)

assert(isstruct(nodeOffsetTable));
assert(isstruct(nodeOffsetTable.Transmitter,'string'));
assert(isstruct(nodeOffsetTable.Receiver,'string'));
assert(isstruct(nodeOffsetTable.Offset,'double'));

[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX_2;

lookingForACK = 0;

% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';

for run = 1 : 1e8
    
    %MAC
    [~, previousMessage] = MACLayerReceiver(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        lookingForACK,...
        previousMessage...
        );
    
    
end

end