function s = ClockConfigCapiT()

%   Copyright 2011-2012 The MathWorks, Inc.

    s = struct( ...
        'refSource',    RefSourceCapiEnumT(0), ...
        'ppsSource',    PPSSourceCapiEnumT(0), ...
        'ppsPolarity',  PPSPolarityCapiEnumT(0) ...
        );
end
