function BER = runSDRuQPSKReceiver(prmQPSKReceiver)

%   Copyright 2012 The MathWorks, Inc.

%#codegen
persistent hRx hSDRu
if isempty(hRx)
    hRx = sdruQPSKRx( ...
        'DesiredAmplitude',             1/sqrt(prmQPSKReceiver.Upsampling), ...
        'ModulationOrder',              prmQPSKReceiver.M, ...
        'DownsamplingFactor',           prmQPSKReceiver.Downsampling, ...
        'CoarseFrequencyCompFFTSize',   prmQPSKReceiver.CoarseFrequencyCompFFTSize, ...
        'PhaseRecoveryLoopBandwidth',   prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
        'PhaseRecoveryDampingFactor',   prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth',  prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
        'TimingRecoveryDampingFactor',  prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
        'PostFilterOversampling',       prmQPSKReceiver.Upsampling/prmQPSKReceiver.Downsampling, ...
        'PhaseErrorDetectorGain',       prmQPSKReceiver.PhaseErrorDetectorGain, ...
        'PhaseRecoveryGain',            prmQPSKReceiver.PhaseRecoveryGain, ...
        'TimingErrorDetectorGain',      prmQPSKReceiver.TimingErrorDetectorGain, ...
        'TimingRecoveryGain',           prmQPSKReceiver.TimingRecoveryGain, ...
        'FrameSize',                    prmQPSKReceiver.FrameSize, ...
        'BarkerLength',                 prmQPSKReceiver.BarkerLength, ...
        'MessageLength',                prmQPSKReceiver.MessageLength, ...
        'SampleRate',                   prmQPSKReceiver.Fs, ...
        'DataLength',                   prmQPSKReceiver.DataLength, ...
        'ReceiverFilterCoefficients',   prmQPSKReceiver.ReceiverFilterCoefficients, ...
        'DescramblerBase',              prmQPSKReceiver.ScramblerBase, ...
        'DescramblerPolynomial',        prmQPSKReceiver.ScramblerPolynomial, ...
        'DescramblerInitialConditions', prmQPSKReceiver.ScramblerInitialConditions,...
        'PrintOption',                  true);

    hSDRu = comm.SDRuReceiver('192.168.10.2', ...
    'CenterFrequency',       prmQPSKReceiver.USRPCenterFrequency, ...
    'Gain',                  prmQPSKReceiver.USRPGain, ...
    'DecimationFactor',      prmQPSKReceiver.USRPDecimationFactor, ...
    'SampleRate',            prmQPSKReceiver.USRPFrontEndSampleRate, ...
    'FrameLength',           prmQPSKReceiver.USRPFrameLength, ...
    'OutputDataType',        'double');
end

% Initialize variables
currentTime = 0;
len = uint32(0);
BER = NaN;
corruptSignal = complex(zeros(4000,1));

while currentTime <  prmQPSKReceiver.StopTime
    % Keep accessing the SDRu System object output until it is valid
    while len <= 0
        [corruptSignal, len] = step(hSDRu);
    end
    % When the SDRu System object output is valid, decode the received
    % message
    if len > 0
        BER= step(hRx, corruptSignal);
    end
    % Update simulation time
    currentTime = currentTime + prmQPSKReceiver.FrameTime;
    len=uint32(0);
end

release(hRx);
release(hSDRu);



